package unpar.topcoder.electronicstore_01.model

import unpar.topcoder.electronicstore_01.R

object  AllProducts {
    val products = arrayOf<ProductDetails>(
        ProductDetails("Galaxy Note", ProductCode.PNEW, ProductCode.SMARTPHONE, 4000000,
            R.drawable.note_1, R.drawable.note_2, R.drawable.note_3, "Produk ini dijual terpisah dengan charger dan earphonenya, karena charger dan earphonenya dibutuhkan. Happy shopping."),
        ProductDetails("Galaxy Note 2", ProductCode.PNEW, ProductCode.SMARTPHONE, 5000000,
            R.drawable.note2_2, R.drawable.note2_2, R.drawable.note2_3, "Masih baru, tapi pemilik bosan jadi dijual, spek android masih sempurna."),
        ProductDetails("Galaxy Note 3", ProductCode.PNEW, ProductCode.SMARTPHONE, 6000000,
            R.drawable.note3_1, R.drawable.note3_2, R.drawable.note3_3, "Produk ini memiliki daya tahan hingga 5 hari tanpa charge, tapi chargernya dijual terpisah"),
        ProductDetails("Galaxy Note 4", ProductCode.PNEW, ProductCode.SMARTPHONE, 7000000,
            R.drawable.note4_1, R.drawable.note4_2, R.drawable.note4_3, "Silahkan dibeli, produk ini masih disegel pabrik dan terjamin keasliannya"),
        ProductDetails("Galaxy Note 7. 6.1 Galaxy Note Fan Edition", ProductCode.PMEDIUM, ProductCode.SMARTPHONE, 8000000,
            R.drawable.note7_1, R.drawable.note7_2, R.drawable.note7_3, "Produk ini sudah dipakai sekitar 3 bulan sebelumnya, tombol home agak macet meski masih bekerja"),
        ProductDetails("Galaxy Note 8", ProductCode.PNEW, ProductCode.SMARTPHONE, 9200000,
            R.drawable.note8_1, R.drawable.note8_2, R.drawable.note8_3, "Galaxy note 8 memiliki diagonal layar berukuran 8 inch, serta daya tahan baterai yang cukup kuat. produk ini dijual setelah pemakaian 1 minggu, dijual karena pemilik berganti hp"),
        ProductDetails("Galaxy Note 9", ProductCode.PHIGH, ProductCode.SMARTPHONE, 10000000,
            R.drawable.note9_1, R.drawable.note9_2, R.drawable.note9_3, "Masih baru, segel original Samsung, garansi 6 bulan"),
        ProductDetails("Galaxy Note 10", ProductCode.PHIGH, ProductCode.SMARTPHONE, 11000000,
            R.drawable.note10_1, R.drawable.note10_2, R.drawable.note10_3, "Galaxy note 10 termasuk pen masih dalam kondisi 90% baru, pemakaian 1 minggu. Dijual termasuk charger dan earphone kabelnya"),
        ProductDetails("Galaxy Note 10+", ProductCode.PNEW, ProductCode.SMARTPHONE, 12000000,
            R.drawable.note10p_1, R.drawable.noet10p_2, R.drawable.note10p_3, "Galaxy note 10+ merupakan versi upgrade dari galaxy note 10 yang sama-sama memiliki pen di dalamnya. Produk ini masih dalam kondisi 100% baru"),
        ProductDetails("Galaxy Note 20", ProductCode.PNEW, ProductCode.SMARTPHONE, 13500000,
            R.drawable.noet20_1, R.drawable.note20_2, R.drawable.note20_3, "Galaxy note keluaran terbaru versi 20, including pen didalamnya. Produk ini masih 100% baru (segel Samsung), dijamin harga termurah!"),
        ProductDetails("Galaxy Note 20+", ProductCode.PNEW, ProductCode.SMARTPHONE, 9000000,
            R.drawable.note20p_1, R.drawable.note20p_2, R.drawable.note20p_3, "Versi upgrade dari Galaxy note 20, memiliki fitur tambahan layar edge, lebih premium dilengkapi dengan design yang mewah"),
        ProductDetails("Galaxy Note20 Ultra 5G", ProductCode.PNEW, ProductCode.SMARTPHONE, 18999000,
            R.drawable.note20u_1, R.drawable.note20u_2, R.drawable.note20u_3, "Dijual produk baru, masih segel samsung, perangkat ini mampu mendukung penggunaan sinyal 5G. Dapatkan sebelum kehabisan"),
        ProductDetails("Galaxy A53 5G", ProductCode.PMEDIUM, ProductCode.SMARTPHONE, 5999000,
            R.drawable.a53_1, R.drawable.a53_2, R.drawable.a53_3, "Produk sudah dipakai 2 minggu, kondisi perangkat masih mulus, tapi earphonenya dijual terpisah"),
        ProductDetails("Galaxy Tab 7.0", ProductCode.PHIGH, ProductCode.TABLET, 7000000,
            R.drawable.tab7_1, R.drawable.tab7_2, R.drawable.tab7_3, "Tablet keluaran lama, sudah tidak diproduksi lagi saat ini. Produk sudah termasuk dengan charger dan earphone"),
        ProductDetails("Galaxy Tab 4 7.0", ProductCode.PHIGH, ProductCode.TABLET, 8000000,
            R.drawable.tab4_1, R.drawable.tab4_2, R.drawable.tab4_3, "Tablet ini sudah tidak diproduksi lagi di pasaran, tapi kondisinya masih bagus, tidak ada lecet sedikitpun, baru dipakai 1 minggu"),
        ProductDetails("Galaxy Tab Pro 10.1", ProductCode.PHIGH, ProductCode.TABLET, 8699000,
            R.drawable.tab10_1, R.drawable.tab10_2, R.drawable.tab10_3, "Dijual terpisah dengan charger dan earphonenya, selamat membeli."),
        ProductDetails("Galaxy Tab Pro 12.2", ProductCode.PHIGH, ProductCode.TABLET, 9999000,
            R.drawable.tab12_1, R.drawable.tab12_2, R.drawable.tab12_3, "Produk ini keluaran terbaru dengan layar ultra HD dilengkapi dengan kemampuan untuk konek ke keyboard. Dijual terpisah dengan keyboardnya"),
        ProductDetails("Galaxy TabPro S", ProductCode.PHIGH, ProductCode.TABLET, 10999000,
            R.drawable.tabpro_1, R.drawable.tabpro_2, R.drawable.tabpro_3, "Tablet edisi pro yang memiliki layar lebih luas serta ram yang lebih besar dibandingkan dengan tablet edisi lainnya."),
        ProductDetails("Galaxy Tab S8+ (Wi-Fi)", ProductCode.PMEDIUM, ProductCode.TABLET, 9999000,
            R.drawable.tab8_1, R.drawable.tab8_2, R.drawable.tab8_3, "Dapatkan segera galaxy tab S8+ yang hanya mendukung jaringan WiFi ini, sangat praktis untuk dibawa kemanapun dan kapanpun"),
        ProductDetails("Samsung Galaxy Watch", ProductCode.PMEDIUM, ProductCode.WATCHES, 9999000,
            R.drawable.watch_1, R.drawable.watch_2, R.drawable.watch_3, "Jam tangan dari samsung ini sudah dipakai selama 5 bulan, kondisi masih bagus meski ada sedikit lecet pada badgenya"),
        ProductDetails("Samsung Galaxy Watch Active", ProductCode.PMEDIUM, ProductCode.WATCHES, 10999000,
            R.drawable.watcha_1, R.drawable.watcha_2, R.drawable.watcha_3, "Produk ini memiliki sensor pemantau kesehatan seperti denyut nadi, kalori terbakar, dan beberapa fitur lainnya lagi"),
        ProductDetails("Galaxy Watch4 LTE (40mm)", ProductCode.PLOW, ProductCode.WATCHES, 11500000,
            R.drawable.watch4_1, R.drawable.watch4_2, R.drawable.watch4_3, "Design yang cantik & fitur yang canggih. Dapatkan segera !"),
        ProductDetails("Galaxy Watch Active 2", ProductCode.PHIGH, ProductCode.WATCHES, 10399000,
            R.drawable.watcha2_1, R.drawable.watcha2_2, R.drawable.watcha2_3, "Dapatkan segera produk ini sebelum kehabisan, stok terbatas"),
        ProductDetails("Galaxy Buds", ProductCode.PMEDIUM, ProductCode.GALAXYBUDS, 1699000,
            R.drawable.buds_1, R.drawable.buds_2, R.drawable.buds_3, "ear buds premium dengan harga miring, dapatkan segera"),
        ProductDetails("Galaxy Buds Plus", ProductCode.PMEDIUM, ProductCode.GALAXYBUDS, 2500000,
            R.drawable.budsp_1, R.drawable.budsp_2, R.drawable.budsp_3, "Design produk ini lebih baik daripada yang lainnya, memiliki garansi 3 bulan"),
        ProductDetails("Galaxy Buds Live", ProductCode.PMEDIUM, ProductCode.GALAXYBUDS, 2899000,
            R.drawable.budsl_1, R.drawable.budsl_2, R.drawable.budsl_3, "Dapatkan segera produk ini sebelum kehabisan"),
        ProductDetails("Galaxy Buds Pro", ProductCode.PMEDIUM, ProductCode.GALAXYBUDS, 3000000,
            R.drawable.budspro_1, R.drawable.budspro_2, R.drawable.budspro_3, "Dapatkan segera sebelum kehabisan, produk ini dijual lengkap dengan garansinya (sisa 3 bulan lagi)"),
        ProductDetails("Galaxy Buds2", ProductCode.PMEDIUM, ProductCode.GALAXYBUDS, 3500000,
            R.drawable.buds2_1, R.drawable.buds2_2, R.drawable.buds2_3, "Ear buds dari samsung ini memiliki performa yang sangat baik, suara 3d yanng dihasilkan mampu mengubah dunia anda, sempat jatuh sekali")
    )
}

